#!/bin/bash
INTERFACE="${BLOCK_INSTANCE:-eth0}"

if [[ $(ip -o -4 addr show dev $INTERFACE) == "" ]]; then
    echo "eth down" 
    echo "#FF0000"
    echo "#FF0000"
else
    ip -o -4 addr show dev $INTERFACE | python2 -c "import sys; print sys.stdin.read().split()[3].split('/')[0]"
    echo "#00FF00"
    echo "#00FF00"
fi
