#!/bin/bash
result=$(ip tuntap show)
# [[ -z $result ]] && (echo 'vpn down') || (echo "$result"; echo "#FF00000")
if [[ -z $result ]]; then
	echo 'vpn down'
	echo "#FF00000"
	echo "#FF00000"
else
	echo "vpn up"
	echo "#00FF00"
	echo "#00FF00"
fi
